image: node:alpine
pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - mv dependencygraph.html public/
    - cp src/NotFound.js public/404.html
  artifacts:
    paths:
      - public
  only:
    - telephone
variables:
  PUBLIC_URL: "/kwitter"